### ISSUE TITLE
mogus

### ISSUE THREAD

**Issue by brannanz** [NoTextToSpeech/goofy-site#16]
im mogussing your susy blasl @NoTextToSpeech

**Comment by discowd-nitwo** [comment]
what is that even supposed to mean...

**Comment by brannanz** [comment]
@discowd-nitwo it means i stole your Winner

**Comment by discowd-nitwo** [comment]
you make no sense

**Comment by brannanz** [comment]
do you know who joe is

**Comment by Githuboffical123** [comment]
Joe Who? I dont know!

**Comment by brannanz** [comment]
@Githuboffical123  joe mama
